# Site settings
title: The Cloud Architects
description: 'A podcast about cloud, technology and the people using it'
url: 'https://thecloudarch.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'The Cloud Architects'
  email: /contact/
  twitter_username: thecloudarch
  facebook_username: thearchitects.cloud
  github_username:  thecloudarch
  linkedin_username:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
